# Generated by Django 5.2.dev20241101104349 on 2024-11-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_calendar', '0002_rename_events_event_rename_subjects_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='aa', max_length=5),
            preserve_default=False,
        ),
    ]
