# Generated by Django 5.2.dev20241101104349 on 2024-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_calendar', '0003_subject_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_white_text',
            field=models.BooleanField(default=0),
        ),
    ]
